### ISSUE TITLE
구글 Analyitics를 설정 파일 형태로 설정할 수 있었으면 합니다.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#100]
모든 페이지에 구글 Analytics에 필요한 javascript 코드를 넣을 수 있도록 했으면 하는데요, 다양한 환경에서 적용시키기 위해서 파일 등으로 외부 설정으로 할 수 있었으면 합니다.

**Comment by hoony-o-1** [comment]
모든 페이지에 넣기 위한 작업은 백본안에 갖추어 놓았는데요, 다양한 환경이란게 어떤건지, 외부 설정으로 한다면 어떤 식의 예가 있을지 보여주시면 감사하겠습니다

**Comment by spikeekips** [comment]
지금도 analytic 관련 코드가 페이지에 포함되어 있던데요, 간단히 말해서 원하는 ga 코드를 넣을 수 있었으면 좋겠고, 그 방법이 설정 파일에서 지정할 수 있었으면 좋겠다는 의견이에요.

**Comment by spikeekips** [comment]
:+1:

**Comment by spikeekips** [comment]
헛 잘못 닫았어요. :) 죄송.

**Comment by hoony-o-1** [comment]
아하 페이지마다 다른 ga 코드를 넣는다는 말씀이죠?

**Comment by spikeekips** [comment]
@hoonch3 페이지 마다는 아니구요, 페이지 하단에, 'XXXX'로 되어 있는 코드를 설정에서 지정하고 싶다는 얘기에요.

**Comment by hoony-o-1** [comment]
음 view 단에서 config를 빼보는 것은 처음인데, express 에서 잡고있는 `/config/config.js` 파일처럼 `/public`안에 일단 `config.js`넣었어요. 이게 아니라면 백본 안에 config를 잡아야 하니 원래 어떻게 보통 잡으시는지 알려주세요

**Comment by spikeekips** [comment]
혹시 /public 이면 외부에서 접근할 수 있는 위치인가요? 그렇다면 접근할 수 없는 위치로 지정해주세요.

**Comment by hoony-o-1** [comment]
view에서 script를 집어넣을 때 외부에서 접근할 수 없는 위치를 어떻게 잡나요?

**Comment by spikeekips** [comment]
제가 말씀드린 config는 일종의 global config인데요, 이런 식이죠.

```
 [global config file]
         |
         |
         ▼
      [node]
         |
         |
         ▼
     [frontend]
```

**Comment by hoony-o-1** [comment]
아 이해했네요 현재 config 파일을.그대로 활용하면 될 듯 합니다 #113 이슈에서 진행할게요

**Comment by spikeekips** [comment]
😄

**Comment by kangminc** [comment]
GA코드가 잘 작동하는지 테스트해볼 수 있을까요? 아래 코드로 부탁드립니다.
SCRIPT
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61309870-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
/SCRIPT

**Comment by hoony-o-1** [comment]
설정했습니다. url 확인이 필요하겠네요

**Comment by kangminc** [comment]
:+1:

**Comment by spikeekips** [comment]
@kkm-kcij 이 이슈는 GA 코드 작동 여부를 확인하는 게 아니라, 설정파일로 지정할 수 있게 하는 #113 과 관련된 이슈입니다

**Comment by spikeekips** [comment]
#113이 닫혔으니 함께 닫을께요.
