### ISSUE TITLE
검색결과 표시 오류

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#101]
한번 국방부로 검색한 이후에 박근혜로 검색했는데, 잠시 동안 박근혜  1건이 표시된 다음에 이전에 검색했던 국방부 명단이 같이 표시됩니다.

![image](https://cloud.githubusercontent.com/assets/7311404/14519337/25a9587c-0259-11e6-9c22-0e737e9113dd.png)

**Comment by kangminc** [comment]
(검색 결과가 처음 표시된 화면)
![image](https://cloud.githubusercontent.com/assets/7311404/14520454/906c4a56-025f-11e6-8df3-54e838daecb0.png)

이 화면에서 '박근혜'라고 다시 검색했더니 마찬가지로 표시됩니다.
'뒤로 가기'를 누르면 검색이 풀린 첫 화면이 아니라, 사이트에 접속하기 전의 화면(새탭)으로 나갑니다.

**Comment by hoony-o-1** [comment]
적용

**Comment by kangminc** [comment]
👍
