### ISSUE TITLE
select 박스에서 아래 화살표를 누를 수 없어요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#102]
<img width="335" alt="screen shot 2016-04-14 at 4 39 04 pm" src="https://cloud.githubusercontent.com/assets/174565/14520458/998b2878-025f-11e6-86b9-05f9665ca7d4.png">
눌러도 반응이 없어요.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
👍
