### ISSUE TITLE
특정 width에서 파이차트의 크기 조정

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#103]
아래와 같이 표시될 때가 있습니다.

![image](https://cloud.githubusercontent.com/assets/7311404/14522384/49f0eed8-0269-11e6-8881-8da10f110995.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by kangminc** [comment]
👍  일단 주요 사이즈(폰, 아이패드, pc)에서 해결된 상태인데, 추후 더 나은 해법 없는지 찾아봤음 해요

**Comment by kangminc** [comment]
#21 에서 테이블 적용하면서 함께 닫습니다.
