### ISSUE TITLE
모바일버전 검색 결과 리스트페이지에서 재산 상세 내역페이지 전환 시 문제

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#105]
![image](https://cloud.githubusercontent.com/assets/14939610/14547436/7ea3637a-02e8-11e6-808a-c9a7d4f6e5d5.png)
모바일 버전에서 검색 결과 리스트 페이지에서 재산 상세내역을 보기를 하면 
개별 상세 내역이 먼저 보이지 않고 검색 영역이 먼저 보입니다.
상세내역이 상단에 보여져야 할 것 같습니다.

**Comment by hoony-o-1** [comment]
수정했어요. 새로고침 후 한번 테스트 부탁드려요

**Comment by kangminc** [comment]
제 안드로이드에서는 잘 작동합니다

**Comment by kangminc** [comment]
미정님 6s에서는 여전히 발생하네요. 0.1초 정도 잠깐 동안 상세내역이 표시된 다음에 바로 검색 영역이 표시됩니다

**Comment by leshem8** [comment]
저도 이제 제대로 보여요~

**Comment by leshem8** [comment]
아니네요.. 제대로 보일때도 있고 아닐때도 있고 그래요

**Comment by kangminc** [comment]
제 핸드폰에서도 다시 발생합니다. 안드로이드에서는 항상 검색 영역이 표시됩니다

**Comment by kangminc** [comment]
제 폰에서는 이제 여러번 해도 잘 됩니다. @gracemj 님 확인부탁드려요

**Comment by kangminc** [comment]
아이폰 6에서 확인했습니다. 수고하셨어요 :+1:
