### ISSUE TITLE
모바일 버전 상단 두번째 바 유지 문제 

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#106]
![image](https://cloud.githubusercontent.com/assets/14939610/14547486/29f6e148-02e9-11e6-991a-c10055693d00.png)
모바일 버전 메인 페이지 외에는 최상단에 뉴스타파CI대신 제목'고위공직자 '재산 정보 공개'을 표시하기로 했었는데요.
두번 반복해서 넣을 필요는 없을 것 같습니다.
(PC버전이랑 다르게 적용 될 필요가 있을 것 같습니다)

**Comment by spikeekips** [comment]
지금처럼 스크롤이 되면 가려지는 게 자연스러울 거 같아요. :)
