### ISSUE TITLE
푸터 위쪽 하얀색 바 생김

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#108]
![image](https://cloud.githubusercontent.com/assets/14939610/14547934/60b4ec58-02ed-11e6-90ab-6fec89d0b4e0.png)
![image](https://cloud.githubusercontent.com/assets/14939610/14547946/7ac48b94-02ed-11e6-9807-c804b2794307.png)
배경색이 있는 페이지에서 푸터 위 하얀색 바 가 생깁니다.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
