### ISSUE TITLE
메인 화면 아래에 여백이 너무 없어요

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#110]
![2016-04-15 10 52 14](https://cloud.githubusercontent.com/assets/7311404/14549154/4f9a9c82-02f8-11e6-8a10-0badce3cb9ff.png)

**Comment by kangminc** [comment]
11인치 맥북 사파리에서 전체화면한 크기였어요

**Comment by hoony-o-1** [comment]
적용

**Comment by kangminc** [comment]
:+1:
