### ISSUE TITLE
기본 검색 시 옵션내용 중복

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#111]
'국회' 가 두번 들어갑니다

**Comment by hoony-o-1** [comment]
이건 데이터 상 문제같네요 확인해볼게요

**Comment by kangminc** [comment]
20대 총선 당선자들의 소속(1)이 비어있는데, 관련 있는 건지 확인 부탁드려요

**Comment by kangminc** [comment]
👍

**Comment by spikeekips** [comment]
이 문제는 데이터 문제가 아니라 기본 검색 옵션, 소속기관 선택에 `국회`가 두번 들어간다는 내용이에요. 

![image](https://cloud.githubusercontent.com/assets/174565/14588043/8c0b84de-04fa-11e6-9eac-e3f5f288ea3a.jpeg)

**Comment by hoony-o-1** [comment]
이건 강민님이 지적한 문제가 맞는데 데이터를 다시 올리다가 다시 반복된 문제에요. 적용하고 코멘트 남길게요

**Comment by kangminc** [comment]
👍
