### ISSUE TITLE
Global 설정 파일에 담길 내용을 정리했어요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#113]
#100 과 이어진 내용이에요. 어떤 것들을 설정할지 정리했어요.
- Google Analytics GA 코드
- DB 설정: host, port, user, password, db name
- SMTP 설정: host, port, user, password, tls 혹은 ssl 사용 여부

이것 외에도 있으면 추가해주세요.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
https://github.com/codenamu/official-assets-explorer/commit/9fd5147473f6ba462f4dab6a31c1776c345195ec#diff-ff1772f82f6193393f756ba18ae4288aR39 확인해주세요.

**Comment by hoony-o-1** [comment]
5395301a50e8d07d4a3060c29b275934cea57204 

확인 부탁드려요~

**Comment by spikeekips** [comment]
https://github.com/codenamu/official-assets-explorer/commit/5395301a50e8d07d4a3060c29b275934cea57204#diff-ff1772f82f6193393f756ba18ae4288aR69 :)

**Comment by hoony-o-1** [comment]
앗 죄송 적용했어요

**Comment by spikeekips** [comment]
👍
