### ISSUE TITLE
당선자 검색에서, `/api/official?election=1`이 너무 오래걸려요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#114]
결과가 나오는데 늦게 걸리길래 한번 테스트해봤어요.

```
$ time curl -so /tmp/1.json 'http://128.199.128.104:3000/api/official?election=1'
real    0m4.491s
user    0m0.005s
sys 0m0.012s
```

내용을 살펴보니, 아마도 한페이지에 표시할 40개 정도가 아니라, 전체 결과를 모두 뱉어내는 것 같아요. 아마도.
![screen shot 2016-04-15 at 1 44 55 pm 2](https://cloud.githubusercontent.com/assets/174565/14551677/2856b250-0311-11e6-87f3-3eae3b253484.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
여전히 `officials` 목록 개수가 1117개네요.

**Comment by hoony-o-1** [comment]
좀 바보같은 짓을..ㅋㅋ 적용했어요

**Comment by spikeekips** [comment]
👍
