### ISSUE TITLE
당선자 검색에서 `/api/official?election=1` 을 두번 요청하는 문제가 있어요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#115]
당선자 검색으로 검색한 뒤, 페이지를 다시 읽으면 `/api/official?election=1`를 두번 호출하네요. 특별한 이유가 없다면, 한번만 호출하도록 변경했으면 해요.

![screen shot 2016-04-15 at 4 55 28 pm 2](https://cloud.githubusercontent.com/assets/174565/14555072/63e1c142-032b-11e6-8c92-56a83bf7ba29.png)

**Comment by hoony-o-1** [comment]
이건 눈에 보이는 원인을 모르겠네요. 좀 살펴봐야겠습니다

**Comment by hoony-o-1** [comment]
수정

**Comment by spikeekips** [comment]
👍
