### ISSUE TITLE
이름으로 검색했을 때, 관련 없는 인물들이 표시됩니다.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#117]
<img width="1075" alt="screen shot 2016-04-16 at 11 29 56 pm" src="https://cloud.githubusercontent.com/assets/174565/14581575/45dbbc1a-042b-11e6-8dbc-5d7604c3e5c6.png">

**Comment by kangminc** [comment]
사이트를 처음 켠 후에 이름으로 검색하면 해당하는 사람만 나옵니다. 그 다음에 이름 검색을 계속 이어서 해도, 해당하는 사람들만 표시됩니다.

검색창을 빈 칸인 채로 검색해서 전체 사람들을 띄운 다음에 다시 이름으로 검색하면, 해당하는 사람이 맨 먼저 표시되고 다른 사람들(아마도 전체)이 그 뒤에 계속 표시됩니다.
조직명으로 검색한 다음에 이름으로 검색하면, 마찬가지로 해당 이름의 사람과 이전에 검색했던 조직의 사람들이 함께 표시됩니다.

**Comment by kangminc** [comment]
잘 작동하네요 :+1:  @spikeekips 님도 확인부탁드려요

**Comment by spikeekips** [comment]
:+1:
