### ISSUE TITLE
노무현, 대통령 직위 문제

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#118]
![image](https://cloud.githubusercontent.com/assets/174565/14587975/63f152e6-04f8-11e6-9704-037e0a7afd15.jpeg)

노무현의 경우 박근혜, 이명박과는 다르게 최종 직위가 대통령이 아니라 해양수산부 장관으로 나옵니다.

**Comment by kangminc** [comment]
open16798 노무현, open16799 한명숙의 소속(3)을 수정해줘야 합니다. 각각 대통령, 국무총리로.

**Comment by kangminc** [comment]
두 건밖에 안되니까 손으로 수정해주시는 게 나을 것 같네요.

**Comment by kangminc** [comment]
:+1:
