### ISSUE TITLE
상세페이지 표현 수정

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#12]
- [x] 상세페이지의 '경력' -> '재산 공개 이력'
- [x] '포트폴리오' -> '자산 구성비'
- [ ] 자산분류에서 '항공기' -> '자동차 등'

**Comment by kangminc** [comment]
'포트폴리오' -> '자산 구성비'
자산분류에서 '항공기' -> '자동차 등'

**Comment by hoony-o-1** [comment]
자산 분류는 데이터 이슈라서, 2016년 데이터 종합해주실 때 반영해주세요 :+1:
