### ISSUE TITLE
당선자 검색에서 검색 옵션을 다시 지정했을 때 결과가 바뀌지 않아요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#121]
당선자 검색에서 검색한 뒤, 조건을 비꾸고 검색해도 결과가 바뀌지 않아요.
![image](https://cloud.githubusercontent.com/assets/174565/14588116/39c2a75a-04fc-11e6-853e-788744d58e5e.jpeg)

**Comment by hoony-o-1** [comment]
수정 적용

**Comment by spikeekips** [comment]
@hoonch3 이제는 당선자 검색에서 검색 조건이 작동하지 않네요. 모든 당선자들이 나오는 듯.

<img width="1016" alt="screen shot 2016-04-18 at 3 29 19 pm" src="https://cloud.githubusercontent.com/assets/174565/14595467/76675498-057a-11e6-9263-7d866a7619fe.png">

**Comment by hoony-o-1** [comment]
앗 모바일 위주로 테스트하다보니 제 불찰이네요 수정할게요

**Comment by hoony-o-1** [comment]
반영했어요

**Comment by spikeekips** [comment]
👍
