### ISSUE TITLE
경력 내용이 검색 결과와 상세 페이지가 다르게 나와요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#123]
![image](https://cloud.githubusercontent.com/assets/174565/14589099/cacb180a-0514-11e6-9011-5311a3bc0d30.jpeg)
![image](https://cloud.githubusercontent.com/assets/174565/14589100/cb097334-0514-11e6-8e81-e3943b32dbe8.jpeg)

상세에서는 년도별로 같은 경력을 묶어서, 검색 결과에서는 풀어서 표현되어 있어요. 머 결국 내용은 동일하지만, 동일하게 표현하면 좋겠어요.

**Comment by hoony-o-1** [comment]
이것도 오늘 반영할게요

**Comment by hoony-o-1** [comment]
반영했어요
1. 디자인이 필요할듯
2. 이번 총선 당선자의 경우 텍스트가 상당히 기네요

**Comment by spikeekips** [comment]
지금처럼 년도를 이어서 표시하면 될 것 같아요. 긴 경력들이 꽤 있네요. 여튼, 👍  😄
