### ISSUE TITLE
검색 입력폼이 두 개가 생겨요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#124]
![image](https://cloud.githubusercontent.com/assets/174565/14589193/ef1fbfd8-0516-11e6-8456-b5f11674a531.jpeg)

http://128.199.128.104:3000/#?keyword=%EC%83%88%EB%88%84%EB%A6%AC%EB%8B%B9%22%2C%22%EB%8B%B9%EC%84%A0%EC%9E%90%22 .

**Comment by hoony-o-1** [comment]
오잉 무슨 환경에서 이러는가요?

**Comment by spikeekips** [comment]
검색어는 `새누리당","당선자"`. 적절하게 escape해주시면 될 듯.

**Comment by hoony-o-1** [comment]
escape 로직 추가했어요. `,`는 whitespace로 나머지 심볼은 전부다 escape 시켰는데 한번 테스트부탁 ^^

**Comment by spikeekips** [comment]
음, 대신 `제1차장` 등 숫자까지 함께 없애버리는 것 같아요. `제1차장`은 `제차장`으로 바뀌어서 검색되네요.

**Comment by hoony-o-1** [comment]
반영했어요~ 테스트부탁드려요

**Comment by spikeekips** [comment]
👍
