### ISSUE TITLE
기본검색 시 옵션 기본문구 오류

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#126]
![image](https://cloud.githubusercontent.com/assets/14939610/14593464/a3c03af0-0565-11e6-910a-c029d9273354.png)
기본검색 시 옵션 기본문구 중 '연도를 선택하세요'가 '0개의 항목'으로 보입니다.

**Comment by hoony-o-1** [comment]
#120, #126, #127 유사 이슈, native에서 다른 라이브러리를 적용했으니 확인 부탁드려요

**Comment by hoony-o-1** [comment]
적용했어요~!
