### ISSUE TITLE
기본검색 시 옵션 된 항목 표시

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#127]
![image](https://cloud.githubusercontent.com/assets/14939610/14593509/24aaaf10-0566-11e6-96be-35e79394f417.png)
소속 선택을 1개 선택했는데 2개항목이라고 표시됩니다.
선택 된 내용은 아래에서 보여지므로 검색선택 부분은 항상 기본 문구가 보여지는게 맞는 것 같습니다.
'소속을 선택하세요' '연도를 선택하세요' 이렇게요

**Comment by hoony-o-1** [comment]
#120, #126, #127 유사 이슈

native에서 다른 라이브러리를 적용했으니 확인 부탁드려요

**Comment by hoony-o-1** [comment]
적용했어요~!
