### ISSUE TITLE
검색 결과 화면에 표시되는 인물 대표이력 오류

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#128]
대표 이력이 최근이 아니라 과거 이력으로 표시
![image](https://cloud.githubusercontent.com/assets/7311404/14598212/16d79b7a-058c-11e6-8824-36c879b129c1.png)

소속이 2줄이 될 경우 직위가 표시되지 않음
![image](https://cloud.githubusercontent.com/assets/7311404/14598304/796862a6-058c-11e6-8b45-d833c9be6294.png)

**Comment by hoony-o-1** [comment]
적용했어요~!

**Comment by kangminc** [comment]
:+1:
