### ISSUE TITLE
모바일에서 기본 검색 옵션 선택할 경우 키보드 표시 없애기

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#130]
이런 식으로 타자칠 때 처럼 키보드가 표시됩니다. 화면을 너무 가려서 표시하지 않는 게 좋을 것 같아요.

![screenshot_2016-04-19-14-07-46](https://cloud.githubusercontent.com/assets/7311404/14628424/d5c117e4-0638-11e6-86bf-f49586ad3cc9.png)

**Comment by hoony-o-1** [comment]
적용했어요~!

**Comment by kangminc** [comment]
:+1:
