### ISSUE TITLE
당선자 검색 옵션에서 선택한 항목이 아래 선택 항목에 표시되지 않아요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#131]
<img width="552" alt="screen shot 2016-04-20 at 4 57 54 pm" src="https://cloud.githubusercontent.com/assets/174565/14667283/7ece6ba8-0719-11e6-841c-4262444fde92.png">

**Comment by hoony-o-1** [comment]
수정했습니다 :)

**Comment by kangminc** [comment]
:+1:
