### ISSUE TITLE
모바일버전 선택 옵션UI

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#134]
![image](https://cloud.githubusercontent.com/assets/14939610/14779777/a4f32734-0b14-11e6-80a8-a9a10f2bb642.png)

아이폰6S에서 당선자 검색 옵션UI는 현재 네이티브 UI로 적용되어있는데 기본 검색이 위와 같이 보입니다.
옵션 박스도 화면 스크롤시 검색 옵션 바 상하로 왔다 갔다 합니다.

**Comment by hoony-o-1** [comment]
네이티브 UI는 '소속을 선택해주세요' 대신에 '0개 항목이 선택되었습니다'가 강제되는 문제로 일단 다른 라이브러리를 사용하고 있는 상태에요. 현재로서는 둘중 하나를 선택해야 할 것 같아요.placeholder냐 네이티브 UI냐.

**Comment by leshem8** [comment]
네이티브 UI를 사용하는게 좋을듯합니다.
당선자 검색은 네이티브 UI사용하고있고.. 기본검색도 같은 방식으로가시죠~

**Comment by hoony-o-1** [comment]
적용해보았으니 한번 테스트 부탁합니다

**Comment by leshem8** [comment]
![image](https://cloud.githubusercontent.com/assets/14939610/14971403/d7527556-110c-11e6-8669-771d030fc279.png)
기본검색과 당선자검색에 적용된 네이티브 UI의 선택사항 정렬(하나는 좌측 하나는 중앙)과 가운데 텍스트 위아래 보더 유무의 차이가 있는데 다르게 한 이유가 있을까요?

**Comment by hoony-o-1** [comment]
native UI를 사용했기 때문에 제가 임의로 디자인을 손보진 않았구요..

두개의 차이라면 왼쪽은 multi select, 오른쪽은 single select 옵션을 준 정도에요
또 왼쪽은 placeholder를 주려고 봤더니 safari iOS 에 에러들이 좀 있어서 options들을 따로 optgroup으로 묶은게 있구요
