### ISSUE TITLE
모바일 버전 자산분류 레이아웃

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#135]
![image](https://cloud.githubusercontent.com/assets/14939610/14808567/3ffc61a8-0bc1-11e6-9151-608b916df4e0.png)
분류항목이랑 내용이랑 상하 라인을 맞추어야 할 것 같습니다.
'항목'은 세로로 정렬되네요.
아이폰 6s화면입니다.

**Comment by hoony-o-1** [comment]
테이블을 모바일인 경우 가로로 정렬하느냐 세로로 정렬하느냐도 있어요, 이번에는 세로로 그냥 데스크탑이랑 동일하게 맞춰보았는데 둘중하나를 선택해주세요. 위의 이슈는 해결되었다고 가정하구요.

**Comment by leshem8** [comment]
네 그럼 데스트탑이랑 동일하게 맞추어주시면 될것같아요

**Comment by hoony-o-1** [comment]
네 한번 확인해주세요 예시페이지: http://128.199.128.104:3000/#up46341?keyword=
