### ISSUE TITLE
소개페이지 표 디자인

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#139]
![image](https://cloud.githubusercontent.com/assets/14939610/14976882/8c2cba26-114a-11e6-9923-a98c2b729bae.png)
현재 데탑버전과 모바일에서 보이는 화면입니다. 아래 이미지 처럼 수정해주세요.
모바일은 항목을 줄이든지 어떻게 해결해야 할 것 같아보이는데 @amoebakim 님 어떻게할지 정해서 모바일에 저렇게 길게 세로로 한줄로 보이지는 않게 해야할 것 같아요

![image](https://cloud.githubusercontent.com/assets/14939610/14976876/7eda4a8c-114a-11e6-9455-aacfe1f4734b.png)

**Comment by kangminc** [comment]
모바일에서는 연도와 합계 정도만 표시하는 게 가능할까요?

**Comment by hoony-o-1** [comment]
모바일은 세로가 아닌 가로로 빠지도록 적용해서 모든 컬럼 다넣어둔 상태에요 확인 부탁드려요

**Comment by gracemj** [comment]
![image](https://cloud.githubusercontent.com/assets/14939610/15101542/448d80f0-15ce-11e6-914c-13406d90e889.png)
모바일에서 자산분류 width가 너무 좁아서 항목이 여러개가 있다는 걸 잘 모를 것 같아요. 좀 잘리더라도 좀 넒게해서 다른 내용이 보여지게 하는 건 어떨까요? 자산분류 정렬도 왼쪽으로 약간 더 갔으면 합니다.
