### ISSUE TITLE
서비스가 다운된 것 같아요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#14]
<img width="626" alt="screen shot 2016-03-30 at 2 59 27 pm" src="https://cloud.githubusercontent.com/assets/174565/14133192/11fc0824-f688-11e5-8cd8-3eb298f65ee4.png">

**Comment by hoony-o-1** [comment]
잠시 디비가 내려갔었더라구요 :) 다시 올렸어요

**Comment by spikeekips** [comment]
:+1:
