### ISSUE TITLE
데이터 설문조사 디자인 스타일 

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#140]
검색에 사용된 선택 폼이나 스타일로 통일하는게 좋을 것 같습니다.

![image](https://cloud.githubusercontent.com/assets/14939610/14976964/2c18de2a-114b-11e6-9b7e-24c4c17179e9.png)

![image](https://cloud.githubusercontent.com/assets/14939610/14976962/253425c4-114b-11e6-96a5-d188651de984.png)

**Comment by leshem8** [comment]
모바일 버전도 같은 형식으로요. 너무 이질감이 들어요 ㅠ

**Comment by hoony-o-1** [comment]
적용

**Comment by kangminc** [comment]
:+1:
