### ISSUE TITLE
연락하기 페이지 디자인

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#141]
![image](https://cloud.githubusercontent.com/assets/14939610/14977080/1ead3f3c-114c-11e6-9b28-12c0b902d422.png)
기존에 잡았던 부분이 틀어져서 배경으로 색 적용되었던 부분이 일부분만 적용되었고
구분 항목의 텍스트가 두줄로 보입니다.

**Comment by hoony-o-1** [comment]
적용

**Comment by kangminc** [comment]
:+1:
