### ISSUE TITLE
간헐적으로 검색 폼이 나타나지 않아요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#15]
테스트는,
- safari 9.1 Mac OSX 11.14
- chrome 49(64bit) Mac OSX 11.14

![screen shot 2016-03-30 at 4 50 19 pm 2](https://cloud.githubusercontent.com/assets/174565/14135330/dd7357a0-f697-11e5-93a1-12ed2d28c92c.png)

**Comment by hoony-o-1** [comment]
백본 모델에 자체적으로 버그가 있는데 해결한 줄 알았는데 여전히 그러네요. 해결책을.모색해볼게요

**Comment by spikeekips** [comment]
아직도 문제가 계속되고 있네요. 이번에는 새로운 에러 메세지에요.

<img width="904" alt="screen shot 2016-04-01 at 11 08 55 am" src="https://cloud.githubusercontent.com/assets/174565/14195955/6cc1bd44-f7fa-11e5-83f1-910b1f2c1c41.png">
<img width="916" alt="screen shot 2016-04-01 at 11 09 26 am" src="https://cloud.githubusercontent.com/assets/174565/14195954/6cbdbda2-f7fa-11e5-9188-e1f50847ef72.png">

**Comment by hoony-o-1** [comment]
collection들이 모델을 참조해서 모델에 해당하는 디비에 ajax call을 날리는 식인데, collection 선언시에 model 프로퍼티로 잡혀있는 녀석들을 collection.fetch 요청을 할 때 가끔씩 무시할 때가 있어요. 일단 fetch 요청 전에 model을 한번 더 잡아주는 방법으로 해결했는데 근본적인 해결책은 아닌듯 싶어요

**Comment by spikeekips** [comment]
@hoonch3 네, :+1:  확실히 발생하는 횟수가 줄어들긴 했네요. 다만, 아직도 드물게나마 발생하네요.

**Comment by hoony-o-1** [comment]
require.js를 버리고 개발환경을 backbone만 사용해서 올렸어요. 해결된 것 같은데 테스트좀 부탁드려요 @kkm-kcij @spikeekips

**Comment by spikeekips** [comment]
@hoonch3 이전보다 훨씬 부드럽게 페이지가 열리네요. :+1:
