### ISSUE TITLE
폰트를 로딩하느라 페이지가 로딩하는 데 오래걸리는 듯해요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#16]
`Noto Sans` 폰트를 지금은 어플리케이션 서버에서 static file로 전송하는데요, 몇 가지 문제가 있는 거 같아요.

폰트 파일 자체가 너무 큰데요, `http://128.199.128.104:3000/font/NotoSansCJKkr-Thin.otf` 이 파일은 크기가 11M 정도인데요, 좀 부담스런 크기인 듯해요. 그래서 직접 전송하는 것보다 구글 cdn ( http://fonts.googleapis.com/earlyaccess/notosanskr.css )을 쓰는 게 어떨까 싶네요.

**Comment by hoony-o-1** [comment]
cdn이.오히려 더 느린걸로 알고있었는데 아닌가보네요? 넵 반영할게요

**Comment by spikeekips** [comment]
자체 서버가 충분히 빠르고 성능도 사정이 낫다면 CDN 보다 좋겠지만, 지금은 파일 크기가 충분히 크고, 앞으로 사용자가 많아지만, 서버 부담이 커질 것 같아요.
