### ISSUE TITLE
인물 상세 페이지의 제보하기에서 보내기가 실패해요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#19]
<img width="816" alt="screen shot 2016-03-31 at 9 02 26 am" src="https://cloud.githubusercontent.com/assets/174565/14161547/8f404fa6-f71f-11e5-810a-a08f5044eb92.png">

이것도 구현 중이라면 닫아주세요. ㅎㅎ

**Comment by hoony-o-1** [comment]
data@newstapa.org를 data.newstapa.org 라고..ㅋㅋㅋ
