### ISSUE TITLE
인물 상세 페이지에서 `재산총액` 이 0으로 표시됩니다.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#20]
인물 상세 페이지라 열리면, `재산 총액`이 0으로 표시됩니다. 여기서 아래 `재산 변동 이력`의 막대기 하나를 선택하면 해당 년도의 재산 총액이 나타나네요. 마지막 데이터를 기준으로 총액을 표시하는 게 어떨까 싶어요.
<img width="575" alt="screen shot 2016-03-31 at 9 06 38 am" src="https://cloud.githubusercontent.com/assets/174565/14161670/8d8a404e-f720-11e5-9a85-007f3959ce5d.png">

**Comment by hoony-o-1** [comment]
오 이거 했던거 같은데 안돼있네요~ 적용!

**Comment by hoony-o-1** [comment]
가장 최근 년도를 선택해서 보여주도록 이미 되어있는데 이게 데이터상의 문제?로 2015년 재산정보가 0원이라서 그런 것 같아요. 이건 데이터쪽에서 해결해야할 문제같으니 확인해볼게요

**Comment by spikeekips** [comment]
:+1:
