### ISSUE TITLE
포트폴리오의 파이 챠트의 label들이 겹쳐서 나타납니다.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#21]
<img width="763" alt="screen shot 2016-03-31 at 9 12 51 am" src="https://cloud.githubusercontent.com/assets/174565/14161761/10e338ec-f721-11e5-8d62-917a30454a7f.png">

http://128.199.128.104:3000/up29722

**Comment by spikeekips** [comment]
좀더 나은 방법을 생각해봤어요.
- pie chart의 각 영역을 색으로 구분,
- 수치 % 값은 지금처럼 chart 영역에 그대로 표시
- label은 legend로 옆에 표시
- 종류는 총 39개
- 상위 다섯개 종류(`자동차/선박 등`, `토지`, `채무`, `건물 예금`)를 명료한 색으로
- 나머지 34개는 몇 가지 색을 기준으로 농도차이로 구분.

**Comment by kangminc** [comment]
시기마다 말이 달라서 종류 수가 많아진 것 같은데, 동시에 표시되는 경우로 보면 13개 표시되는 경우가 가장 많은 경우입니다. 박덕흠 2016년, 유천호 2008년 등

**Comment by spikeekips** [comment]
@kkm-kcij 네, 그래도 나오는 것들은 모두 다른 색으로 구분해야겠죠. 같은 색 + 다른 종류라면 사용자들이 혼동할 수 있으니까요.

**Comment by leshem8** [comment]
![image](https://cloud.githubusercontent.com/assets/14939610/14272814/0ef63e3e-fb41-11e5-8338-6943fe3fba3c.png)
1. 자동차/선박 등 fffca9
2. 토지 c0efa9
3. 채무 f4c79c
4. 건물 ffc1d7
5. 예금 b7d1ee
6. c8cef6
7. b6c0e6
8. a9b4dc
9. 9da9cd
10. 909ec2
11. 8493b9
12. 7b8bb1
13. 7a86aa

**Comment by hoony-o-1** [comment]
일단 컬러 변화 없이 라벨링 보여주는 방식만 적용

**Comment by leshem8** [comment]
@hoonch3 색을 둘러싸고 있는 화이트 선은 배경 색과 같은 색으로 해주세요 :)

**Comment by hoony-o-1** [comment]
이게 주신 컬러로 적용하니 웹에서는 전혀 다르게 뜨네요

**Comment by leshem8** [comment]
@kkm-kcij 어떻게 보이는지 스샷 좀 보여주세용~

**Comment by kangminc** [comment]
선이 없으면 헷갈릴 거 같아요. 파이조각과 레이블을 잇는 선은 항상 표시되는 게 좋을 것 같네요. 
![image](https://cloud.githubusercontent.com/assets/7311404/14278539/33fb59e0-fb63-11e5-8dbd-c90eabc6a697.png)

**Comment by hoony-o-1** [comment]
선이 얇아서 1에서 2로 수정하고 내부 % 폰트 키웠어요 확인해보시길

**Comment by spikeekips** [comment]
@kkm-kcij @hoonch3 옷. 이뻐졌어요. 
![image](https://cloud.githubusercontent.com/assets/174565/14281687/8e700846-fb75-11e5-92d1-f91a79c9e84c.jpeg)

**Comment by leshem8** [comment]
선을 넣으신거죠? 선이 직선이면 좋겠어요. 원크기가 좀 큰감이 있는데 줄이고 %나  레이블은 화이트 컬러로 원 밖에 위치시키는 건 어떨까요?

**Comment by hoony-o-1** [comment]
차트 라이브러리를 바꾸면서 레이블 겹치는 문제는 해결되었는데 디자인 시안처럼 %를 빼보려고 하는데 코드가 너무 지저분해 지는 바람에... 곧 적용하면 알려드릴게요 @kkm-kcij 레이블을 잇는 선이 없어지는 문제는 버그였고 해결되었습니다.

**Comment by spikeekips** [comment]
`%` 수치가 회색이라 배경에 묻혀버리네요. @gracemj 님이 정리를 해주셨으면 해요.
![screen shot 2016-04-06 at 8 57 25 am 2](https://cloud.githubusercontent.com/assets/174565/14301862/23ec2c28-fbd6-11e5-920b-ee3d4fdbf8a1.png)

**Comment by leshem8** [comment]
![image](https://cloud.githubusercontent.com/assets/14939610/14272814/0ef63e3e-fb41-11e5-8338-6943fe3fba3c.png)
그림처럼 레이블과 수치는 파이 밖으로 빼고 지금보다 수치와 레이블 폰트가 더 커졌으면 좋겠어요 수치는 레이블 보다 좀 더 크고 굶게 보였으면 좋겠구요. 선의 색도 다 화이트로 레이블 칼라랑 맞췄으면 좋겠어요

**Comment by hoony-o-1** [comment]
레이블 라인 적용, 컬러 및 수치는 미적용

**Comment by hoony-o-1** [comment]
%가 큰 순서대로 정렬하였고 13개 컬러중 상위 5개 칼라만 우선 적용했어요, 나머지 8개는 %순으로 적용해서 알려드릴게요(오늘 내로)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
아직 % 수치들이 그 크기에 따라서 폰트 크기도 함께 표현되지 못하는 것 같아요.

**Comment by hoony-o-1** [comment]
%에 따라 폰트 사이즈가 달라지는 거라면 최소폰트/ 최대폰트 사이즈를 잡아주세요. 허나 지금 파이차트 상 자산 분류 이름이 길고 짧은 경우에 따라 짤리는 경우가 생기니 제 의견은 적당한 사이즈 하나를 동일하게 적용하는게 더 나아보이네요

**Comment by leshem8** [comment]
일단 폰트 사이즈는 그대로 가시죠.

**Comment by spikeekips** [comment]
이 페이지에서 label이 겹치네요. 참고. http://128.199.128.104:3000/#up46341?keyword=
<img width="628" alt="screen shot 2016-04-15 at 9 29 20 am" src="https://cloud.githubusercontent.com/assets/174565/14547876/e4a9c552-02ec-11e6-915c-5faca5915954.png">

**Comment by hoony-o-1** [comment]
1,2 % 좁은 영역 사이에 자동차/선박 등 처럼 긴 이름의 분류가 껴서 생기는 부득이한 경우 같습니다. 현재로서는 1,2% 영역의 분류는 숨김으로써 해결하는 수밖에 없어요. 혹은 위처럼 긴 이름이 1,2%에 들어가는 경우를 감수하고 그대로 가거나요.

**Comment by kangminc** [comment]
제 의견입니다.
-일단 %가 0%이면 제외하는 게 좋을 것 같아요. (이런 경우 http://128.199.128.104:3000/#up36486 )
-글자색을 파이조각 색과 비슷하게 하는 건 어떻게 생각하세요? 저렇게 빽빽한 경우에 어떤 조각이 어떤 레이블인지 판단하는데 도움이 될 것 같아요.
-시간을 두고 다른 차트 라이브러리로 옮겨가는 것이 가능할까요? 아래 링크에서 같은 데이터[1,2,3,4,40,51]를 입력하면 괜찮게 나옵니다.
http://jsfiddle.net/highcharts/dK9CD/ ([참고](http://stackoverflow.com/questions/12603593/dealing-with-pie-chart-label-overlap-highcharts))

**Comment by spikeekips** [comment]
@kkm-kcij 

> -일단 %가 0%이면 제외하는 게 좋을 것 같아요. (이런 경우 http://128.199.128.104:3000/#up36486 )

지금 상세한 연도별 재산내역은 이 파이챠트 외에는 없어요. 0%가 zero를 의미하는 게 아닌 소숫점 아래 자리를 날려서 만들어진 0인만큼 반드시 표시해야한다고 보여져요. 당연히 `0%`가 아니라 생략된 소숫점까지 표시해야겠죠. 

> -글자색을 파이조각 색과 비슷하게 하는 건 어떻게 생각하세요? 저렇게 빽빽한 경우에 어떤 조각이 어떤 레이블인지 판단하는데 도움이 될 것 같아요.

문제는 파이 챠트가 제대로 표현되지 않는다는 점에서 좋은 아이디어인 것 같아요.

**Comment by spikeekips** [comment]
@kkm-kcij @hoonch3 @gracemj 

파이챠트가 재산구성을 보여주는 중요한 역할을 하고 있는데요, 지금 상태로는 표현하는데 충분하지 거 같아요. 일단 임시방편으로 데이터를 충실히 보여주기 위해서 파이챠트 대신 테이블로 대체하면 어떨까합니다. 

| 항목 | 비중 | 금액 |
| --- | --- | --- |
| 건물 | 60% | 2억5천만원 |
| 자동차 | 20% | 8천만원 |
| 증권 | 20% | 8천만원 |

**Comment by hoony-o-1** [comment]
@kkm-kcij 강민님 의견은 어떠신가요?

**Comment by kangminc** [comment]
일단 여기까지로 정리하겠습니다. :+1:
