### ISSUE TITLE
푸터 디자인 수정

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#23]
**푸터 수정**
![footer](https://cloud.githubusercontent.com/assets/14939610/14162576/0ac4ffb6-f728-11e5-853f-3e85a738e368.jpg)
CC by이미지 width:120px;

![footer_mobile](https://cloud.githubusercontent.com/assets/14939610/14162912/52131094-f72b-11e5-9c45-f6a15490a0a4.jpg)

**Comment by hoony-o-1** [comment]
적용 - 서버는 아직

**Comment by spikeekips** [comment]
@hoonch3 지금 width: 100px 로 설정되어 있네요. 참고.

**Comment by leshem8** [comment]
PC에서는 푸터가 브라우저 하단에 붙어야 할 것 같습니다.
아직 모바일 쪽은 햄버거 메뉴 펼침했을때 푸터 내용이 안보입니다.  아래로 당겼다가 놓으면 나타나는데
헴버거 메뉴 펼침에서는 화면이 고정되어야할 것 같습니다.

**Comment by hoony-o-1** [comment]
적용
