### ISSUE TITLE
선택 옵션 리스트 박스 "선택", "해제" 영역 색 표현

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#24]
![image](https://cloud.githubusercontent.com/assets/14939610/14163187/d5872abc-f72d-11e5-915b-5146d74c64c7.png)
![image](https://cloud.githubusercontent.com/assets/14939610/14163292/ecbca530-f72e-11e5-92f7-9caf26e46cd9.png)

선택된 옵션은 그레이로 색 적용되고 해제하면 다시 원래 배경색으로 바뀌어야할 것같은데 
다른 옵션을 선택하기 전 까지 그대로 그레이가 적용되네요.
같은 옵션을 선택했다가 해제하고 다시 선택하면 색이 더 진하게 표시되는 문제도 있구요.

옵션 리스트 마다 체크박스 요소가 있으니
굳이 바형태로 색 적용안되어도 되지않을까요? :)

**Comment by hoony-o-1** [comment]
넵
