### ISSUE TITLE
검색어 입력영역 

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#25]
![image](https://cloud.githubusercontent.com/assets/14939610/14165446/fca474d6-f743-11e5-82d5-90915d4a5c62.png)
- [x] 검색의 입력 박스안 텍스트 좌측 16px 공간을 주세요
- [x] 검색 버튼은 라운딩 제거, 그림자 효과 제거해주세요

**Comment by spikeekips** [comment]
:+1:
