### ISSUE TITLE
"기본 검색" 선택 시 옵션 선택 영역 폭 조절

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#26]
![image](https://cloud.githubusercontent.com/assets/14939610/14165592/98fed9ec-f745-11e5-8ad0-92b196d25f78.png)

![image](https://cloud.githubusercontent.com/assets/14939610/14165577/6956e7a2-f745-11e5-8878-7c688c8f90fe.png)

"기본검색" 선택 시 옵션바 영역을 "총선인물검색" 옵션 바와 width 값을 동일하게 적용하고 가운데 정렬해 주세요.
늘어나니 선택 화살표와 거리가 선택 옵션 값에 비해 너무 떨어진 감이 있습니다.

**Comment by hoony-o-1** [comment]
적용 - 서버는 아직

**Comment by spikeekips** [comment]
:+1:
