### ISSUE TITLE
검색 결과값 요약 문구 스타일

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#27]
![image](https://cloud.githubusercontent.com/assets/14939610/14165891/0f00bfd6-f749-11e5-8877-9e70a7dc4fb3.png)
`
    font-size: 20px;
    letter-spacing: -0.05em;
}
`
- [x] 위 아래 패딩값 글씨 높이 2배 이상 주세요.
- [x] 개수 표시하는 숫자는 font weight 300으로 해주세요.
- [x] 문구가 한 문장이고 이어지는 문장이 없을 경우에는 "."는 안해되됩니다 :)

**Comment by hoony-o-1** [comment]
font-weight 300은 얇은 두께라서 700으로 설정해두었어요, 서버적용은 아직

**Comment by spikeekips** [comment]
:+1:
