### ISSUE TITLE
검색 결과 리스트 배경 색 

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#28]
배경색은 아래 값으로 바꿔주세요. 
`
{
    background-color: #e7e9ed;
}
`
![image](https://cloud.githubusercontent.com/assets/14939610/14166186/193527fa-f74c-11e5-9950-5c6159b3389d.png)

**Comment by hoony-o-1** [comment]
적용 - 서버는 아직

**Comment by spikeekips** [comment]
서버에도 적용되었네요. :+1:
