### ISSUE TITLE
제목 누르면 검색화면 표시하기

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#30]
제목을 누르면 검색 화면을 표시: 소개, 연락하기 등의 영역에서 검색 화면으로 가려면 헤더의 로고를 클릭해야 하는데, 보통은 제목 부분을 먼저 누를 것 같습니다. 

![untitle](https://cloud.githubusercontent.com/assets/7311404/14167001/0a33deca-f753-11e5-8dd6-fd878593068c.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
