### ISSUE TITLE
 리스트 박스 스타일

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#33]
![image](https://cloud.githubusercontent.com/assets/14939610/14168440/6481e390-f75d-11e5-91ff-6f4f2d4f0105.png)
- [x] 그림자 효과
  `
  box-shadow: 1px 2px 2px 0 rgba(0,0,0,0.1);
  `
- [x] 경력 영역의 아래 스타일은 빼주셔되 될 것 같아요
  .card .card-action {
  border-top: 1px solid rgba(160,160,160,0.2);
  }
- [x] card-link-to-btn의 버튼은 그림자 효과 제거
  ">"도 더 상하로 벌어진 모양이었으면 좋겠는데..
- [x] 인물 이름 표시 
  `
  {
    font-weight: 500;
    font-size: 26px;
    letter-spacing: -0.06em;
    color: rgb(52, 59, 70);
  }
  `
- [x] 현 직위 표시
  `
  {
    font-size: 14px;
    font-weight: 400;
    letter-spacing: -0.03em;
  }
  `
- [x] 경력텍스트 표시는 아래와 같이 해주세요, 목록스타일 점은 4px 지름의 원으로 해주세요
  `
  {
  color: #7b7b7b;
  font-size: 14px;
  padding: 20px 0px 20px 30px;
  letter-spacing: -0.03em;
  }
  `

**Comment by leshem8** [comment]
@hoonch3 리스트 박스 내의 화살표 아이콘 원의 영역은 지름 28px로 해주시고, 경력 텍스트와 같은 열의 상하 중앙, 우측 정렬로 해주세요. 화살표 좌측의 여백이 많이 생기네요.
![image](https://cloud.githubusercontent.com/assets/14939610/14308441/2568bea0-fc11-11e5-95c4-91d00b81b7c8.png)

**Comment by spikeekips** [comment]
:+1:
