### ISSUE TITLE
상세 결과값 페이지 상단 기존 검색 영역 유지

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#34]
상세 결과 페이지에도 상단 기존 검색 영역을 유지하기로 했었어요.

![image](https://cloud.githubusercontent.com/assets/14939610/14169161/3521ba86-f761-11e5-8539-f0ee07fe57b4.png)

![image](https://cloud.githubusercontent.com/assets/14939610/14169198/6da6f704-f761-11e5-9438-96b02d515ec8.png)

**Comment by hoony-o-1** [comment]
#34, #35 는 연결된 문제인데 이부분은 시간이 좀 필요할 듯 합니다.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1
