### ISSUE TITLE
상세 결과 페이지 카드섹션 위 목록보기 

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#35]
![image](https://cloud.githubusercontent.com/assets/14939610/14169232/9e019af8-f761-11e5-9064-99b746ea3c9e.png)
상세 결과 페이지 카드섹션 위 "목록보기"가 없어요

![image](https://cloud.githubusercontent.com/assets/14939610/14169269/c9aa0d84-f761-11e5-9162-e577cd390958.png)

**Comment by hoony-o-1** [comment]
#34, #35 는 연결된 문제인데 이부분은 시간이 좀 필요할 듯 합니다.

**Comment by hoony-o-1** [comment]
아 이 화면은 데스크탑 화면이죠? 모바일에서는 없애고. 일단 추가할게요.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
👍
