### ISSUE TITLE
막대그래프의 세로축 눈금선 단위 변경

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#36]
막대그래프의 세로축 표시 단위가 현재 유동적으로 표시됩니다. (창 크기 변동될 때마다 변경됨.) 이걸 각 사람의 재산 규모 등을 고려해서 한번 표시되면 바뀌지 않도록 고쳤으면 합니다.

예를 들어, 공개된 기간 중 가장 높은 재산 액수가 100억인 사람의 경우에 25억, 50억, 75억, 100억 정도만 표시하되, 창의 크기와 상관없이 저렇게만 표시되도록 바꿨으면 좋겠습니다.
구체적으로 어떤 게 가능할지 잘 모르겠는데, 의견 주세요

**Comment by kangminc** [comment]
0 줄이고 축 위쪽에 (억원), (만원) 표시하는 것 가능할까요?

**Comment by hoony-o-1** [comment]
이것은 월요일에 다시 대화료..

**Comment by hoony-o-1** [comment]
적용

**Comment by kangminc** [comment]
:+1:
