### ISSUE TITLE
세부페이지 재산총액 표시 방식 변경

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#37]
- [x] 지금 천원 단위로 숫자가 표시되는 숫자를 이해하기 쉬운 방식으로 수정했으면 합니다.
  1,723,505 ==> 17억 2350만 5천원
- [x] 기준년도를 함께 표시해주면 좋겠습니다.
  17억 2350만 5천원 | 2015년

**Comment by hoony-o-1** [comment]
했어요
