### ISSUE TITLE
일부 인물 데이터 오류

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#40]
데이터에서와 다르게 표시되는 경우가 있습니다.
아래 박근혜 2016년의 경우, 데이터에는 총계 35억, 건물 25.3억 예금 9.89억으로 되어있는데, 건물이 2번 나오고 합계 50억 이상으로 나옵니다. 확인 부탁드려요
http://128.199.128.104:3000/up41133?org=%EC%A4%91%EC%95%99%EB%B6%80%EC%B2%98+%EB%B0%8F+%EC%82%B0%ED%95%98%EA%B8%B0%EA%B4%80&keyword=%EB%B0%95%EA%B7%BC%ED%98%9C
![image](https://cloud.githubusercontent.com/assets/7311404/14242719/80633cbc-fa8c-11e5-86dd-2277dac2505c.png)

**Comment by hoony-o-1** [comment]
최신 데이터 반영 완료
