### ISSUE TITLE
'제보하기', '연락하기' 폼에서 label이 겹쳐서 보여요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#41]
![image](https://cloud.githubusercontent.com/assets/174565/14274236/216a4a38-fb4b-11e5-9247-9915bdaf904d.jpeg)
![image](https://cloud.githubusercontent.com/assets/174565/14274237/21c3818e-fb4b-11e5-912b-7386565b5759.jpeg)

Label과 Placeholder가 겹쳐보이네요.

**Comment by spikeekips** [comment]
'연락하기'에서는 고쳐졌네요.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
👍
