### ISSUE TITLE
상세페이지에서 뒤로가기했을 때, 드물게 페이지가 검은 레이어가 씌워지네요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#42]
![image](https://cloud.githubusercontent.com/assets/174565/14274334/9f341fb6-fb4b-11e5-8416-21bdabebb817.png)

**Comment by spikeekips** [comment]
목록에서도 비슷한 현상이 나타나네요. 

![image](https://cloud.githubusercontent.com/assets/174565/14274353/c58a0f0e-fb4b-11e5-893c-2b6793ff75fb.png)

**Comment by hoony-o-1** [comment]
#50 중복

**Comment by spikeekips** [comment]
#50 과 같은 증상이라면, #50 과 함께 닫을께요.

**Comment by hoony-o-1** [comment]
테스트부탁드립니다

**Comment by spikeekips** [comment]
옷. :+1:
