### ISSUE TITLE
목록에 인물 약력에서 의미 없는 글자가 포함되어서 나타납니다.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#44]
아마도 원본 저료에서 그대로 표시되는 듯. 
![image](https://cloud.githubusercontent.com/assets/174565/14274548/fa404a14-fb4c-11e5-92a9-d2e4259602ee.jpeg)

**Comment by hoony-o-1** [comment]
@kkm-kcij 이 문제는 데이터 쪽에서 한번 정제가 가능할까요?

**Comment by kangminc** [comment]
데이터에 수정해놨습니다! 오늘자 새 파일로 저장해놨어요

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
아직까지는 여전히 나타나네요.

**Comment by kangminc** [comment]
제 자리에서도 아직.. https://github.com/codenamu/official-assets-explorer/issues/58 이것도 같은 경우예요. 4·16에서 가운데 점이 일관되게 수정되어 있습니다. 확인부탁드려요

**Comment by spikeekips** [comment]
:+1:
