### ISSUE TITLE
모바일 버전 햄버거 메뉴 패널

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#45]
- [x] - 메뉴 패널이 잘려서 안보이네요
- [x] - 최상단 바 (CI,햄버거버튼,sns아이콘) 영역은 메뉴가 펼쳐져도 유지되어야 할 것 같아요. 닫기 액션을 할때도 있는게 더 좋을듯요

![img_2146](https://cloud.githubusercontent.com/assets/14939610/14274567/18c09e08-fb4d-11e5-9ca0-af3317921490.jpg)
![image](https://cloud.githubusercontent.com/assets/14939610/14274644/8ccd438c-fb4d-11e5-8327-4b849b9fa214.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
