### ISSUE TITLE
모바일 버전 검색 영역

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#46]
- [x] 검색어 입력 폼 이어 새도우 효과 빼주세요.
- [x] "검색"폰트도 더 크고 두껍게 해주세요.

![img_2142](https://cloud.githubusercontent.com/assets/14939610/14275496/72e4cada-fb52-11e5-8d2e-80be6528ae48.jpg)
![image](https://cloud.githubusercontent.com/assets/14939610/14275505/89f395e4-fb52-11e5-84d9-937bbe0ccdf7.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
