### ISSUE TITLE
상세페이지가 열리는 재산변동이력 막대 그래프 중 최근 막대가 선택되도록. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#47]
페이지가 열리고 포트폴리오 파이 챠트는 (아마도) 최신 재산변동 이력을 기준으로 일단 표시되는 듯한데요, 최신 재산변동 이력 중 최신 년도 막대가 노란색으로 선택되지 않아 어떤 년도로 표시되었는지 알 수가 없네요. 

![image](https://cloud.githubusercontent.com/assets/174565/14275893/e70a0670-fb55-11e5-930f-03b9c2de77a2.jpeg)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
👍
