### ISSUE TITLE
총선 인물 검색 결과가 정확하지 않아요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#49]
스샷만 보시면 이해할 수 있을 듯. 

![image](https://cloud.githubusercontent.com/assets/174565/14276411/bf8e0840-fb59-11e5-84c2-da4d0944dc14.jpeg)

**Comment by hoony-o-1** [comment]
아 조건문이 잘못 들어가있었네요 대박

적용

**Comment by spikeekips** [comment]
:+1:
