### ISSUE TITLE
iPad PRO에서 드물게 햄버거 메뉴가 나타납니다. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#50]
버그라면 버그, 잘하면 특수기능으로 우길 수도 있는, 좀 애매한... 재연은 간단해요. 굳이 아패프로가 아니라도 가능할 듯. 햄버거 메뉴 버튼이 나타나지 않는 터치 디스플레이를 가진 화면 왼쪽 끝에서 오른쪽으로 쓸면 나타나요. (iOS에서 뒤로 가기 기능)

![image](https://cloud.githubusercontent.com/assets/174565/14276899/a8ba45f0-fb5b-11e5-9c57-58b53507b054.jpeg)

**Comment by hoony-o-1** [comment]
왠지 #42 이슈와 같은 이슈같은데 42에서도 뒤로가기 시 슬라이드 기능을 사용하셨나요?

**Comment by spikeekips** [comment]
@hoonch3 생각해보니 그렇군요. 정확한 통찰이십니다. :smile:

**Comment by hoony-o-1** [comment]
테스트 필요해요 부탁합니다

**Comment by spikeekips** [comment]
@hoonch3 지금도 현상은 계속.

**Comment by spikeekips** [comment]
#42 와 함께 해결되었어요.
