### ISSUE TITLE
총선인물 검색 결과에는 출마지를 표시해야겠어요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#51]
일단 총선인물 검색은 선거구 기준이 아니라 법정명 기준이라 정작 결과에서 출마 선거구를 알 수가 없네요.

**Comment by hoony-o-1** [comment]
혹시 제가 놓친 디자인 파일이 있나요? 출마 선거구가 적용된?

**Comment by spikeekips** [comment]
@hoonch3 이 이슈는 기능개선으로 올린거에요. @kkm-kcij 님 의견을 포함해서 넣을 지 결정하면 좋겠어요.

**Comment by kangminc** [comment]
데이터 상에서 처리 예정. 총선 관련 인물의 최근 소속을 정당명으로, 직위 정보를 지역구 정보로 변경할 것.

**Comment by kangminc** [comment]
당선자들의 경우, 최근 소속과 직위가 선거정보가 되도록 수정해놨어요

**Comment by kangminc** [comment]
2016년도에 2건 공개되는 사람들의 경우에도 대표 경력으로 정당과 출마지가 표시되게 해주세요.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
정당명과 출마지 등이 표시되어야 하는데요, 지금 '추경호' 처럼 소속이 표시되는 경우가 있어요.

**Comment by hoony-o-1** [comment]
음 적용되었는데 다시 한번 확인해보시겠어요?

**Comment by spikeekips** [comment]
여전히 '추경호'는 '국무조정실'로 표시되네요.

**Comment by kangminc** [comment]
'재산 공개 이력'과 '원본 보기' 쪽에는 총선출마가 아닌 이전 2016년 기록도 넣기로 했었는데, 지금은 빠져 있네요. 
![image](https://cloud.githubusercontent.com/assets/7311404/14551785/6b61c566-0312-11e6-80b2-e2e05907cf1a.png)

**Comment by kangminc** [comment]
원본보기에서 20대 총선 자료(2016년 중 20대 총선 300줄)는 항목을 없애 주세요. (원본 제공시 선거법 위반)

**Comment by kangminc** [comment]
:+1:
