### ISSUE TITLE
데이터 페이지

### ISSUE THREAD

**Issue by hoony-o-1** [codenamu/official-assets-explorer#52]
데이터 페이지에 연결할 주소 혹은 텍스트? 페이지 디자인? 부탁드려요

**Comment by spikeekips** [comment]
@kkm-kcij , @hoonch3 데이터 페이지는 이번 오픈에선 일단 포함시키지 않기로 하지 않았나요?

**Comment by hoony-o-1** [comment]
지난 번에 *월 *일에 공개 예정 이란 텍스트를 보여줬으면 좋겠다고 말씀을 드렸어서요, alert 창이나 모달 정도도 괜찮다고 생각합니다

**Comment by kangminc** [comment]
일단은 모달로 간단한 텍스트만 보여주면 좋겠네요. "데이터는 4월 중 공개할 예정입니다."

**Comment by spikeekips** [comment]
:+1:
