### ISSUE TITLE
총선인물검색 선택하면 어색한 스크롤바가 표시됩니다

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#53]
![image](https://cloud.githubusercontent.com/assets/7311404/14278735/2e40b51c-fb64-11e5-83fc-c29b1b1b2af8.png)

**Comment by hoony-o-1** [comment]
오잉

**Comment by hoony-o-1** [comment]
#59 와 비슷한 문제인 듯, 일단 적용 테스트 부탁해요

**Comment by spikeekips** [comment]
@kkm-kcij 님, 확인해보시고 close해주세요.
