### ISSUE TITLE
'연락하기'로 이메일을 보낸 뒤, 폼 내용이 그대로 남아 있어요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#55]
![image](https://cloud.githubusercontent.com/assets/174565/14282099/c526033e-fb77-11e5-872d-b105651535e3.jpeg)

'보내기'를 누르고 alert 팝업이 나타난 뒤 닫기를 누르면, 입력했던 폼 내용이 그대로 남아 있어요. 닫기를 누르면 메인으로 이동하면 자연스러울 거 같아요.

그리고 alert 내용도 '성공적으로 보냈습니다' 대신, '보내주신 내용을 잘 살펴보겠습니다. 감사합니다.' 정도로 변경하면 좋을 것 같아요. (@kkm-kcij 참고.)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
