### ISSUE TITLE
모바일, 상세페이지에서 좌우 스크롤로 빈공간이 생겨요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#57]
iPhoneS5에서. 스샷 참고. 
![image](https://cloud.githubusercontent.com/assets/174565/14282573/f29bcaae-fb79-11e5-87b5-492e52fcbb96.jpeg)

**Comment by hoony-o-1** [comment]
왜 이러는지 모르겠는데.. 혹시 이런 경험 있으신가요??

**Comment by spikeekips** [comment]
소스를 읽어보니까, 원인을 찾았어요. :smile: 스샷에 나온 것처럼, 포트폴리오 파이 챠트가 넓이를 강제로 잡고 있네요. `100%` 정도로 바꾸면 될 거 같아요. 대신 챠트 오른쪽이 잘리는 문제가 생기는데, 이건 챠트 크기를 다시 조정해주시면 될 거 같구요.

![screen shot 2016-04-06 at 8 13 17 am 2](https://cloud.githubusercontent.com/assets/174565/14301157/6c029aca-fbd0-11e5-917f-b52f52547efb.png)
![screen shot 2016-04-06 at 8 13 32 am 2](https://cloud.githubusercontent.com/assets/174565/14301158/6c488242-fbd0-11e5-9188-9a5721f2cb18.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
