### ISSUE TITLE
'4.16 세월호' 가운데 점 문제

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#58]
@kkm-kcij @hoonch3 참고. 

![image](https://cloud.githubusercontent.com/assets/174565/14282796/020dabfa-fb7b-11e5-85dc-892e014a174f.jpeg)
iOS 8 iPhone5s에서는 가운데 점이 네모가 표시. 

![image](https://cloud.githubusercontent.com/assets/174565/14282812/1043031e-fb7b-11e5-86a2-3d5f80adf829.jpeg)
 iPad Pro, iOS 9.3.1. 가은데 점 제대로 표시.

**Comment by hoony-o-1** [comment]
@kkm-kcij 이 기호를 데이터에서 다른 기호로 대체할 수 있을까요

**Comment by kangminc** [comment]
네. 전체적으로 점검해보는 게 좋을 것 같네요

**Comment by spikeekips** [comment]
:+1:
