### ISSUE TITLE
검색 조건 select 를 선택하면 커서가 깜박거려요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#61]
커서는 보이지만 글자는 입력할 수는 없어요. 
![image](https://cloud.githubusercontent.com/assets/174565/14283209/48ef59c2-fb7d-11e5-9fc8-6675b22a94d8.jpeg)

**Comment by hoony-o-1** [comment]
어떤 경우에 뜨는거죠? 브라우저를 바꿔가면서 보는데도 안보이네요

**Comment by spikeekips** [comment]
iOS, iPhone5s, ipad Pro에서 니타나네요.

**Comment by hoony-o-1** [comment]
input[type=text] readonly 인 경우 원래 cursor가 사라져야 정상인데 ios safari에서 커서가 보이는 버그가 있는데 이게 잡히질 않네요. 이건 내일 한번 더 해결책을 찾아봐야겠어요

**Comment by hoony-o-1** [comment]
#62 관련

**Comment by spikeekips** [comment]
👍
