### ISSUE TITLE
모바일에서 검색조건 select 후 entry 영역이 너무 크게 표시되어 페이지를 덮습니다. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#62]
![image](https://cloud.githubusercontent.com/assets/174565/14283353/0cd63220-fb7e-11e5-9ecd-f4f297f7934a.jpeg)

모바일에서는 OS의 native select entry(http://i.stack.imgur.com/TeSki.jpg)를 사용하는 게 좋을 것 같아요.

**Comment by hoony-o-1** [comment]
모바일 경우 max-height 적용

**Comment by spikeekips** [comment]
모바일에서는 원래 의도대로 모바일 OS의 선택UI를 쓰는 게 좋겠어요.

지금 구현에서 불편한 점은, select 를 누르면 화면이 쥼이 된다는 것, 그리고 선택이 끝나도 쥼은 그대로 남아 있다는 점, 그리고 drop down되는 영역이 가로 세로가 좁은 모바일 화면에서 스크롤 등 불편한 점이 보여요.

**Comment by hoony-o-1** [comment]
줌은 해결했어요, 한결 나아졌는데 모바일 OS의 선택 UI로 갔을 때 디자인이 너무 깨질 것 같아서요. 한번 확인 부탁드려요

**Comment by spikeekips** [comment]
@hoonch3 모바일에서 drop menu가 생각보다 불편한 듯해요. UI 보다는 사용하기 쉽도록하고 이후에 좀더 나은 인터페이스를 고민해보는 게 어떨까 싶어요.

**Comment by spikeekips** [comment]
@hoonch3 지금 적용됐네요. 👍 한가지, 기본 모양은 예전 것을 그대로 살렸으면 해요.
![04c9f13c-fcd9-11e5-8a00-e25b7215c981](https://cloud.githubusercontent.com/assets/174565/14481603/a60331fe-016f-11e6-8b9b-db4eaf49c186.png)

**Comment by hoony-o-1** [comment]
좋은 아이디어네요, native에 디자인을 입힐 생각은 못했는데 적용했습니다

**Comment by spikeekips** [comment]
👍
