### ISSUE TITLE
'연락하기' 폼이 사라지지 않아요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#63]
검색 목록에서 '연락하기'를 누른 뒤, 다시 뒤로가기를 누르면, 스샷처럼 아래 '연락하기' 폼이 그대로 남아 있어요.
![screen shot 2016-04-06 at 8 24 42 am 2](https://cloud.githubusercontent.com/assets/174565/14301283/740f8218-fbd1-11e5-8c03-af938d8d2f65.png)
(스샷은 한번에 보기 위해서 일부러 축소시켰어요.)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
@hoonch3 테스트 서버에 아직 적용되지 않았네요. 앞으로 테스트 서버에 적용된 뒤 적용으로 표시했으면 해요.

**Comment by hoony-o-1** [comment]
이 시간에 확인할 줄 모르고 일괄적용하려고 그랬는데 :open_mouth: 그럴게요 :+1: 
하지만 이건 적용했는데 안될리가 없는데.. 일단 확인해볼게요

**Comment by spikeekips** [comment]
@hoonch3 쟈바스크립트의 경우에 브라우져의 강력한 캐쉬로 예전 파일이 사용되는 경우도 있는 듯.

**Comment by hoony-o-1** [comment]
backbone view 에서 문제였는데 git pull을 안해서 push가 안된걸 모르고있었네요 ㅠㅋㅋ 다시 올렸습니다

**Comment by spikeekips** [comment]
와우. @hoonch3 :+1:
