### ISSUE TITLE
상세페이지의 '제보하기'에서 '보내기'한 뒤 alert 내용도 #55 처럼 바꿨으면 해요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#64]
![screen shot 2016-04-06 at 8 38 29 am 2](https://cloud.githubusercontent.com/assets/174565/14301633/65a84f2c-fbd4-11e5-93a3-1fe94521956c.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
