### ISSUE TITLE
모바일버전 푸터 삭제

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#65]
![img_2145](https://cloud.githubusercontent.com/assets/14939610/14301641/70e06e6a-fbd4-11e5-84e2-f5f17ad221a6.jpg)

사이드 메뉴패널 아래 푸터 내용이 있어 그걸로 푸터 대체 하기로 했었어요.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
