### ISSUE TITLE
모바일 버전 검색 결과문구

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#66]
모바일 버전 검색 결과문구 가운데 정렬해주세요
![img_2147](https://cloud.githubusercontent.com/assets/14939610/14301694/e4b6249c-fbd4-11e5-8e0c-4426ccc880fe.jpg)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
