### ISSUE TITLE
모바일에서 자산 구성비 영역 위 아래 여백이 너무 넓어요. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#69]
![image](https://cloud.githubusercontent.com/assets/174565/14303809/5cf186dc-fbe8-11e5-9215-400c795fc0dc.jpeg)

여백을 줄이는 게 좋겠어요.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
