### ISSUE TITLE
검색 구분 탭간의 이동 시 아래 검색바 영역 위치 상이

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#70]
검색 구분 탭간의 이동 시 아래 검색바 영역 위치 상이합니다.
'총선 인물 검색'으로 이동시 검색 바 영역이 내려갑니다.

![image](https://cloud.githubusercontent.com/assets/14939610/14308515/a58062e6-fc11-11e5-8259-e146f9aa52be.png)

![image](https://cloud.githubusercontent.com/assets/14939610/14308528/b10e2594-fc11-11e5-86e0-71eff78f6bf1.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
