### ISSUE TITLE
검색 옵션 바 폭 조정

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#71]
탭간의 검색 옵션 바 폭을 동일하게 적용해 주세요.

![image](https://cloud.githubusercontent.com/assets/14939610/14309225/0aaa52d6-fc16-11e5-9535-836bfbe1c64e.png)

![image](https://cloud.githubusercontent.com/assets/14939610/14309242/1cb76a36-fc16-11e5-8252-10bcbb1abc27.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
@hoonch3 아직 적용되지 않은 듯. 내일 다시 확인해볼께요.

**Comment by hoony-o-1** [comment]
이슈 한번에 정리해서 푸시하려고 해서요~ 일단 지금까지 한 것들만 지금 올릴게요

**Comment by spikeekips** [comment]
@hoonch3 넹. :smile:

**Comment by spikeekips** [comment]
:+1:
