### ISSUE TITLE
'총선 인물 검색' 시 선택 된 항목 유지

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#72]
'총선 인물 검색' 에도 선택된 항목이 보이도록 하기로 했어요
![image](https://cloud.githubusercontent.com/assets/14939610/14309306/a2d9d590-fc16-11e5-9433-2b8f482fe5b7.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
@gracemj 스샷 예가 잘못된 듯. 

기본 검색에서 선택한 뒤 총선 인물 검색을 선택하면, 기본 검색에서 선택한 내용 대신 총선 인물 검색에서 선택한 내용만 위와 같은 형식으로 표시. 그 반대도 동일. 

다시 기본 검색 -> 총선 인물 검색 -> 기본 검색으로 돌아왔을 때 처음 기본 검색에서 선택한 항목들이 표시된다면 원더풀 :smile:

**Comment by spikeekips** [comment]
총선인물검색에서 자치단체, 시군구, 읍면동까지 선택한 뒤, 시군구를 바꾸면 이전에 선택한 읍면동이 남아 있네요.
![screen shot 2016-04-07 at 8 42 03 am 2](https://cloud.githubusercontent.com/assets/174565/14336247/e0d15946-fc9c-11e5-9982-344e53f817bf.png)
![screen shot 2016-04-07 at 8 42 19 am 2](https://cloud.githubusercontent.com/assets/174565/14336250/e31d3f9e-fc9c-11e5-9392-727f9bef9b9f.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
👍 원더풀~
