### ISSUE TITLE
검색 리스트 현재경력 폰트 사이즈 

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#73]
검색 리스트 내 현재 경력 폰트 사이즈를 12px로 줄였으면 합니다.
애매하게 떨어지는 경우가 있네요
![image](https://cloud.githubusercontent.com/assets/14939610/14309477/aad6f56a-fc17-11e5-96a5-b5af2f1b1ebf.png)

**Comment by hoony-o-1** [comment]
px이 아니라 rem 단위로 적용하여서 1rem 에서 0.9rem으로 축소했어요, 일단 확인 부탁

**Comment by leshem8** [comment]
@hoonch3 네, 좋아요~
폰트자간 조절도 추가해주세요^^
`
style="letter-spacing:` -0.05em:

**Comment by hoony-o-1** [comment]
자간 적용

**Comment by kangminc** [comment]
:+1:
