### ISSUE TITLE
검색결과 리스트 내 이름표시와 개인상세내역의 이름 표시 상이

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#74]
![image](https://cloud.githubusercontent.com/assets/14939610/14336280/2961b8ea-fc9d-11e5-9e7e-b6d97766a2de.png)

이름 표시 폰트 굵기 차이가 있네요. 두 부분 동일하게 해주는게 좋을 것 같아요

**Comment by hoony-o-1** [comment]
적용

**Comment by kangminc** [comment]
:+1:

**Comment by leshem8** [comment]
마지막 수정한 걸로 맞춰주실 주 알았는데 제가 말씀 안드렸네요. 죄송합니다 ^^;
얇은 폰트 쪽으로 맞춰주세요
