### ISSUE TITLE
모바일버전 GNB 디자인 수정

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#77]
![image](https://cloud.githubusercontent.com/assets/14939610/14338383/c75da9d2-fcb1-11e5-9856-f78dc2334b1c.png)
현재 sns아이콘 정렬과 사이즈가 제각각이어서 이 부분 정리하였습니다.
뉴스타파CI도 축약버전으로 변경했어요. 같이 반영 부탁드립니다.
에셋경로
http://adobe.ly/1q7DCpn

**Comment by hoony-o-1** [comment]
사이즈 확인 부탁드립니다. 가로 320 사이즈의 모니터에서는 사이즈가 상당히 어색해보여서요

**Comment by leshem8** [comment]
아이폰 6기준으로 작업된거구요, 750px사이즈입니다

**Comment by hoony-o-1** [comment]
음 반응형으로 768픽셀 기준으로 2버전을 작업하는 중인데 그럼 아이폰 6이하에서는 어떻게 보여야 하나요?

**Comment by leshem8** [comment]
그럼 양 사이드 옆 여백을 10px씩 더 줘서 30px로 잡아주세요

**Comment by hoony-o-1** [comment]
아 제가 여쭤본 부분은 아이폰 6이하 사이즈에서 SNS 버튼 배치가 상당히 어색해보인다는 의미였습니다. 오히려 4s등 작은 사이즈를 기준으로 작업해서 늘렸을 때는 그냥 좌/우 간격이 벌어지는게 어떨까요

**Comment by leshem8** [comment]
그래서 뉴스타파 CI를 줄였던 부분이여서요. 화면 양끝을 기준으로 해주시면 될 것 같습니다.

**Comment by hoony-o-1** [comment]
CI를 줄이더라도 오른쪽 SNS 가로폭 및 margin들이 크다보니 아이폰 4기준으로 절반을 훨씬 넘게 커져버리네요. 한번 확인해주세요. 그리고 지금 네비작업하던 코드가 그대로 올라가서 현재 서버에 보이는 모바일 네비는 무시해주세요

**Comment by hoony-o-1** [comment]
적용

**Comment by leshem8** [comment]
#83과 관련된 내용입니다.

**Comment by hoony-o-1** [comment]
#83 두개가 별개의 이슈가 나뉜게 아니라 공통된 이슈라면 하나만 남겨주시면 감사하겠습니다~
