### ISSUE TITLE
모바일 버전 햄버거 메뉴 펼침부분 

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#78]
- [x] 상단 gnb는 고정이 되어야 할 것 같아요. 보였다 안보였다하는 문제가 있네요. 
- [x] 펼침 메뉴는 모바일 기기의 상하를 꽉채워서 화면이 상하로 안움직이게 했으면 합니다.
- [ ] 펼침 메뉴 뒤의 스크린을 움직이면 메뉴 리스트의 연락하기가 사라졌다를 반복합니다. 메뉴 뒤 화면은 고정이어야 할 것 같습니다.
- [x] 펼침 영역의 푸터영역의 높이를 줄여주세요.
- [x] 카피라이트 문구의 폰트 사이즈를 줄여주세요.
- [x] 메뉴 리스트 선택시 적용되는 회색바가 일정한 색이 아니고 층이 나누어져보입니다. #f3f3f3 색으로 바색이 동일하게 보이게 해주세요.
- [x] 메뉴 리스트의 폰트를 키워주시고 #343b46 색으로 적용해 주세요.

![image](https://cloud.githubusercontent.com/assets/14939610/14340950/aed8fb3a-fcc7-11e5-88ff-4a8305c6825d.png)

**Comment by hoony-o-1** [comment]
메뉴 뒤 화면은 지금도 고정되어 있는데 터치 기기에서 문제가 발생하는가요? 확인부탁드립니다. 나머지는 적용

**Comment by spikeekips** [comment]
@hoonch3 메뉴가 펼쳐졌을 때 뒤 화면은 스크롤 되네요. (iPhone5s)

**Comment by spikeekips** [comment]
👍
