### ISSUE TITLE
모바일 버전 제목영역 디자인 스타일

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#79]
- [x] 대제목 폰트 사이즈 font-size: 2.9rem;
- [x] CC코리아 로고 width:120px, 좌측 텍스트와 상하 중앙 정렬(지금은 텍스트보다 로고가 더 올라가 보여요)
- [x] 제목영역 높이를 아래 이미지 오른쪽 처럼 줄여 주세요. (모바일 기기 한 화면에 검색하기 버튼이 화면 하단에 보여지게 잡았던 부분입니다.)

![image](https://cloud.githubusercontent.com/assets/14939610/14342800/72e2504e-fcd7-11e5-85f6-6c50cac2a38d.png)

**Comment by hoony-o-1** [comment]
다른 디자인 이슈와도 비슷한데 아마 css 수치들이 6 기준이라 4s에서는 어색하고 깨지는 것들이 있네요. 4s기준으로 작업하는게 어떠신가요?

**Comment by hoony-o-1** [comment]
아이폰 4s에 맞게 대제목 사이즈 수정, 확인 필요합니다

**Comment by spikeekips** [comment]
:+1:
