### ISSUE TITLE
일부영역 그림자 스타일 제거

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#80]
아래 캡쳐부분 그림자가 아직 제거가 안되었어요.
모바일 버전 검색영역은 데스크 탑에서는 그림자가 안보이는데 휴대폰에서는 보이네요. 사파리, 크롬 브라우저 모두 보입니다.
![image](https://cloud.githubusercontent.com/assets/14939610/14343015/04c9f13c-fcd9-11e5-8a00-e25b7215c981.png)

**Comment by hoony-o-1** [comment]
적용

**Comment by leshem8** [comment]
모바일 입력 폼은 그림자가 보여요, 메인 페이지 검색하기와 연락하기 부분에도요
