### ISSUE TITLE
모바일버전 파이 그래프 자산종류 텍스트와% 잘려보이는 문제

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#82]
아이폰6에서 아래 이미지 처럼 잘려보입니다.
![image](https://cloud.githubusercontent.com/assets/14939610/14343944/574c2186-fcdf-11e5-8b16-5b63cfc03fff.png)

**Comment by hoony-o-1** [comment]
파이 원 사이즈를 줄여 적용, 확인 필요해요

**Comment by spikeekips** [comment]
@hoonch3 대신 파이 원 크기가 너무 줄어든 듯해요. 파이크기를 줄이는 대신 다른 방법이 필요해 보여요. 

![image](https://cloud.githubusercontent.com/assets/174565/14384579/d0692a4e-fdd6-11e5-8caa-b599da07f400.jpeg)

**Comment by hoony-o-1** [comment]
적용, 파이사이즈 & 텍스트 사이즈 조정했어요. @gracemj 디자인에서 한번 확인 필요할 것 같아요

**Comment by leshem8** [comment]
아직 구성 비율수치 스타일은 좀 더 두껍고 크게 해주시고 자산 종류는 좀 줄여주세요. 둘 사이도 여백을 지금 보다는 더 줘야 할 것 같습니다.

**Comment by spikeekips** [comment]
확인했어요.
