### ISSUE TITLE
모바일버전 메인페이지 외에는 GNB 제목 삽입

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#83]
모바일버전에서는 메인페이지 외 모든 페이지에서 아래 이미지와 같이 CI 위치에 제목을 넣기로 하였습니다.
스크롤 해도 고정영역입니다. 

![image](https://cloud.githubusercontent.com/assets/14939610/14344136/cb920e6a-fce0-11e5-86c2-f6c35d5e7e28.png)

**Comment by hoony-o-1** [comment]
#77 이 이슈와 충돌하는데 확인 부탁드립니다

**Comment by leshem8** [comment]
메인페이지만 #77로 해주시고 이 이슈에서는  CI만 제목으로 교체하고 다른 요소들은 #77에 맞춰주시면 될 것 같습니다.

**Comment by hoony-o-1** [comment]
적용

**Comment by leshem8** [comment]
![image](https://cloud.githubusercontent.com/assets/14939610/14454369/27db067a-00d5-11e6-9542-532d3eda33a4.png)
아이폰 4 기준으로 상단 다시 잡아봤어요~
지금은 작은 화면에서는 겹치는 부분이 있네요
에셋경로 http://dobe.ly/1q7DCpn

**Comment by leshem8** [comment]
#77과 관련된 내용입니다.

**Comment by hoony-o-1** [comment]
다시 한번 확인 부탁드립니다. SNS 아이콘 한개당 58px가 잡혀있는데 58 \* 4 = 232px인데 아이폰 4는 가로 320px이에요.

**Comment by leshem8** [comment]
아, 디자인 작업시 640기준으로 잡아서 그런거 같네요. 반으로 줄여서 생각하시면 될 것 같습니다.

**Comment by leshem8** [comment]
![image](https://cloud.githubusercontent.com/assets/14939610/14547560/2b4f9408-02ea-11e6-909b-4dede566f78c.png)
상단의 제목 자간도 지금 너무 붙어서요. 조금 자간을 늘려주시면 좋겠습니다.

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
:+1:
