### ISSUE TITLE
모바일버전 검색 결과 리스트 상단 '다시 검색하기' 버튼

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#84]
모바일버전 검색 결과 리스트 상단 '다시 검색하기' 버튼을 넣기로하였습니다.
![image](https://cloud.githubusercontent.com/assets/14939610/14344166/f5fc2f00-fce0-11e5-8e48-b5a6c05301c1.png)

**Comment by hoony-o-1** [comment]
적용
