### ISSUE TITLE
'총선인물검색'시 아래 생기는 이미지

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#85]
![image](https://cloud.githubusercontent.com/assets/14939610/14371467/fa70fd44-fd72-11e5-98bb-1a5db5b33c4e.png)
![image](https://cloud.githubusercontent.com/assets/14939610/14371472/076267d6-fd73-11e5-9e5c-1916abbd4e70.png)

**Comment by hoony-o-1** [comment]
@kkm-kcij 님께서 올리셨던 이슈인데 발견되는 환경이 어떤 환경인가요

**Comment by leshem8** [comment]
파폭, 사파리, 크롬 브라우저에서 가로 폭 조절을하면  저 부분이 나타났다 사라졌다합니다. 폭을 줄이면 항상 유지 되구요

**Comment by hoony-o-1** [comment]
네 확인해볼게요

**Comment by hoony-o-1** [comment]
저는 아무리 해도 가로스크롤이 안뜨네요. 일단 감으로... 수정은 해보았으니 테스트 부탁드립니다
