### ISSUE TITLE
헤더 소셜 아이콘 영역 레이아웃이 불안합니다. 

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#88]
스샷 참고. 

![image](https://cloud.githubusercontent.com/assets/174565/14384378/b71f0794-fdd5-11e5-9140-8561925bcaa3.jpeg)
![image](https://cloud.githubusercontent.com/assets/174565/14384379/b787d8b4-fdd5-11e5-8b65-7db1159fe6a6.jpeg)

**Comment by spikeekips** [comment]
참고로 작은 스샷은 iPhone5s, 큰 것은 iPad Pro 가로 모드.

**Comment by hoony-o-1** [comment]
네 다른 이슈에도 남겼는데 이건 아직 작업중이라 아직은 무시해주세요

**Comment by hoony-o-1** [comment]
#77 이슈, 적용

**Comment by spikeekips** [comment]
👍
