### ISSUE TITLE
상단 두번째 바 유지

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#91]
![image](https://cloud.githubusercontent.com/assets/14939610/14415278/2e15b696-ffd8-11e5-924c-4c30911e5d7b.png)

인물 상세 정보에서도 상단으로스크롤 했을때 '고위공직자 재산 정보공개' 가 있는 바 영역이 보이게 하도록 한것같은데요.  뉴스타파 CI링크는 뉴스타파 홈페이지로, '고위공직자 재산 정보공개' 링크는 메인 페이지로 이동하기로 했어요.
그래서 항상 영역을 항상 유지해야할 듯 합니다.

**Comment by hoony-o-1** [comment]
적용
