### ISSUE TITLE
재산 데이터 처리방식 확인

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#92]
정몽준 최근 재산은 2조인데
![image](https://cloud.githubusercontent.com/assets/7311404/14416651/a5e6b954-ffe7-11e5-8efa-023e5bb399f3.png)

93억으로 나옵니다. 확인 부탁드려요.
![image](https://cloud.githubusercontent.com/assets/7311404/14416642/8f3d9a2e-ffe7-11e5-892d-4e5a2db16a5f.png)

**Comment by kangminc** [comment]
안철수도 1600억이 나와야 하는데 너무 작네요.
![image](https://cloud.githubusercontent.com/assets/7311404/14416703/1a629fbe-ffe8-11e5-8b28-5380776e4296.png)

![image](https://cloud.githubusercontent.com/assets/7311404/14416706/24fb0592-ffe8-11e5-9f7c-7bf1879bef86.png)

**Comment by hoony-o-1** [comment]
프로필 사진 비교한 것을 도큐먼트 슬라이드 주소를 가지고 비교하면서 인물이 쪼개져버렸어요. 다시 업뎃하고 알려드릴게요

**Comment by hoony-o-1** [comment]
데이터는 새로 올렸어요, 그런데 데이터에 0원인데 포함되어 있는 자산 종류들이 꽤 있네요, 확인 부탁드려요. 조단위로 넘어갔을 때 바차트 yAxis 단위가 깨지는 이슈는 해결중입니다

**Comment by kangminc** [comment]
:+1:
