### ISSUE TITLE
pc-크롬에서 재산 총액 부분에 스크롤바

### ISSUE THREAD

**Issue by kangminc** [codenamu/official-assets-explorer#96]
![image](https://cloud.githubusercontent.com/assets/7311404/14447278/0c69ad42-0099-11e6-8732-46d3614336f4.png)

**Comment by hoony-o-1** [comment]
확인부탁바랍니다~ 윈도에서만 보이는 스크롤 문제라서요

**Comment by kangminc** [comment]
가로 스크롤바는 남아있는데 의도하신 것 맞나요?
![image](https://cloud.githubusercontent.com/assets/7311404/14487357/12603630-019d-11e6-9a7f-cff944dc935e.png)
