### ISSUE TITLE
메인 검색 페이지 검색 문구, 화살표 안보이는 문제

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#97]
![image](https://cloud.githubusercontent.com/assets/14939610/14452236/467b948a-00c8-11e6-94ba-38bf0a5e8df0.png)
파이어 폭스에서 옵션 디폴트 문구가 안보입니다. 화살표도 안보이구요.
![image](https://cloud.githubusercontent.com/assets/14939610/14452447/a20e3400-00c9-11e6-96c6-22eb107f4f17.png)
크롬에서는 화살표가 안보이구요

**Comment by hoony-o-1** [comment]
적용

**Comment by kangminc** [comment]
:+1:

**Comment by spikeekips** [comment]
👍
