### ISSUE TITLE
검색 폼의 검색 버튼 문구 오류

### ISSUE THREAD

**Issue by leshem8** [codenamu/official-assets-explorer#98]
![image](https://cloud.githubusercontent.com/assets/14939610/14452236/467b948a-00c8-11e6-94ba-38bf0a5e8df0.png)
특정 width에서 검색폼의 버튼에 '검색하'로 보입니다.
박스도 입력 폼과 엇갈리는 문제가 있습니다.

**Comment by hoonch3** [comment]
적용

**Comment by hoony-o-1** [comment]
적용

**Comment by kangminc** [comment]
박스가 입력폼과 엇갈리는 문제는 특정 width에서 아직 남아있는 것 같아요
![image](https://cloud.githubusercontent.com/assets/7311404/14487577/4f9992c0-019e-11e6-9416-900eec188350.png)

**Comment by hoony-o-1** [comment]
해결했어용

**Comment by kangminc** [comment]
:+1:

**Comment by spikeekips** [comment]
👍
