### ISSUE TITLE
'제보하기', '연락하기' 폼에 입력된 내용을 확인하지 않고 있어요.

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#99]
이메일 등 내용을 입력하지 않고 '보내기'를 누르면 아래와 같은 alert 가 나오는데요, form validation도 필요해 보여요. 그리고 alert 메세지로 상황에 맞게 표시해야겠어요.
<img width="961" alt="screen shot 2016-04-13 at 12 06 58 pm" src="https://cloud.githubusercontent.com/assets/174565/14481722/bd89b02c-0170-11e6-848e-b22c893f766f.png">

**Comment by hoony-o-1** [comment]
적용

**Comment by spikeekips** [comment]
👍
